### ISSUE TITLE
Getting error: "S3 error: The specified key does not exist."

### ISSUE THREAD

**Issue by boomiSupport-Stephen** [aws-quickstart/quickstart-boomi-atom#24]
After clicking "Next" on the "Create stack" page, beneath "Specify template" this error message appears:

S3 error: The specified key does not exist. For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Nothing was changed in the template settings, though I tried different regions.

This same error message is displayed regardless of whether I choose to install into a new VPC instance, or choose to install into an existing VPC instance.

**Comment by davmayd** [comment]
This has been resolved.
